/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import Mathlib.Topology.AlexandrovDiscrete
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Fintype.Powerset
import Mathlib.Data.Set.Card
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Logic.Equiv.Sum
import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# The number of topological bases of a finite set

This is the statement of record for a Palomar submission. It states the
compared family (`card_valid_bases`, the small-\(N\) table, the sandwich
bound, discrete dominance, and `#(N) ∼ 2^(2^N-N)`) and the definitions
those theorems mention.
It imports only Mathlib. The proofs are in `CARDB.lean`, `CARDB/SmallN.lean`
and `CARDB/Asymptotics.lean`, and are compared against this file by
Comparator.

## Informal claim

Let `α` be a finite type (an `N`-element set). Write `Top(α)` for the set of
topologies on `α`, and write `#(α)` for the number of families
`B ⊆ Set α` that are topological bases on `α` in the usual point-set sense:

1. **Covering.** `⋃₀ B = univ`.
2. **Intersection.** For `U, V ∈ B` and `x ∈ U ∩ V` there is `W ∈ B` with
   `x ∈ W ⊆ U ∩ V`.

These are the two axioms in Mathlib's `IsTopologicalBasis`, without the
`eq_generateFrom` clause that fixes a topology in advance. The topology
generated by `B` is Mathlib's `generateFrom B`.

Every finite topology `τ` is Alexandrov-discrete, so each point `x` has a
minimal open neighbourhood `nhdsKer {x}`. The **canonical minimal basis**
`M_τ` is the set of these neighbourhoods. Bases generating `τ` are exactly
the families `B` with `M_τ ⊆ B ⊆ {U | τ.IsOpen U}`, so the fiber over `τ`
has size `2^(|τ| − |M_τ|)`. Summing over topologies gives

$$
\#(\alpha) = \sum_{\tau \in \operatorname{Top}(\alpha)} 2^{\lvert\tau\rvert - \lvert M_\tau\rvert}.
$$

`card_valid_bases` is that identity: `Fintype.card (ValidBasis α)` equals
that sum. Here `opensOf τ` is the set of `τ`-open sets (so
`ncard (opensOf τ)` is `|τ|`) and `minimalBasis τ` is `M_τ`.

The discrete topology contributes \(2^{2^N-N}\) bases. Every other
topology on an \(N\)-element set with \(N\ge 2\) has at most
\(3\cdot 2^{N-2}\) open sets, and there are at most \(2^{N(N-1)}\)
topologies, which gives the sandwich
`card_valid_bases_bounds`. The relative error is at most
\(2^{N^2-2^{N-2}}\), so `#(N) ∼ 2^{2^N-N}`
(`card_valid_bases_asymptotic`). For \(N\ge 10\) the error term is at
most the discrete term (`card_valid_bases_dominated`). Kernel-reducible
enumeration gives the exact table
`#(0)=2`, `#(1)=2`, `#(2)=10`, `#(3)=142` (`card_valid_bases_small`).

The identity is parameterized by `[Fintype α]` only (`DecidableEq` is
omitted, as in `CARDB.lean`). The table and bounds keep `[DecidableEq α]`.
The empty type is included. Every compared theorem depends on
`propext`, `Classical.choice` and `Quot.sound` only.

## How to read this file

The definitions below are the vocabulary of the claim. A reader who wants to
check *what* has been proved should read this file and need not read anything
else. `Solution.lean` imports the sorry-free development in `CARDB.lean`,
`CARDB.SmallN` and `CARDB.Asymptotics`.
-/

open Set TopologicalSpace Filter Topology
open scoped BigOperators

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- A collection of subsets `B` is a topological basis if it covers `α`
    and satisfies the local intersection property. -/
def IsBasis (B : Set (Set α)) : Prop :=
  (⋃₀ B = univ) ∧
  ∀ ⦃U V⦄, U ∈ B → V ∈ B → ∀ x ∈ U ∩ V, ∃ W ∈ B, x ∈ W ∧ W ⊆ U ∩ V

/-- Families of subsets of `α` that are topological bases. `#(α)` is the
    cardinality of this type. -/
def ValidBasis (α : Type*) [Fintype α] := { B : Set (Set α) // IsBasis B }

/-- Open sets of `t`, as a family of subsets. This map is injective, so there
    are only finitely many topologies on a finite type. -/
def opensOf (t : TopologicalSpace α) : Set (Set α) := {U | t.IsOpen U}

omit [Fintype α] [DecidableEq α] in
theorem opensOf_injective :
    Function.Injective (opensOf : TopologicalSpace α → Set (Set α)) :=
  leftInverse_generateFrom.injective

noncomputable instance instDecidableEqTopologicalSpace : DecidableEq (TopologicalSpace α) :=
  opensOf_injective.decidableEq

noncomputable instance instFintypeTopologicalSpace : Fintype (TopologicalSpace α) :=
  Fintype.ofInjective opensOf opensOf_injective

noncomputable instance instDecidablePredIsBasis : DecidablePred (IsBasis : Set (Set α) → Prop) :=
  fun _ => Classical.dec _

noncomputable instance instFintypeValidBasis : Fintype (ValidBasis α) :=
  Subtype.fintype _

variable (t : TopologicalSpace α)

/-- In a finite topological space, the minimal open neighborhood of `x`
    (Mathlib's `nhdsKer {x}` at topology `t`). -/
abbrev minimalOpen (x : α) : Set α :=
  @nhdsKer α t {x}

/-- The minimal basis `M_T` is the collection of all minimal open neighborhoods. -/
def minimalBasis : Set (Set α) :=
  range (minimalOpen t)

omit [DecidableEq α] in
/-- **Main theorem.** The number of topological bases on a finite type `α`
    equals the sum, over all topologies `τ` on `α`, of
    `2^(|τ| − |M_τ|)`, where `M_τ` is the canonical minimal basis of
    minimal open neighbourhoods. -/
theorem card_valid_bases :
    Fintype.card (ValidBasis α) =
      ∑ τ : TopologicalSpace α,
        2 ^ (ncard (opensOf τ) - ncard (minimalBasis τ)) := by
  sorry

omit [Fintype α] [DecidableEq α] in
/-- Exact table: `#(0) = 2`, `#(1) = 2`, `#(2) = 10`, `#(3) = 142`. -/
theorem card_valid_bases_small :
    Fintype.card (ValidBasis (Fin 0)) = 2 ∧
    Fintype.card (ValidBasis (Fin 1)) = 2 ∧
    Fintype.card (ValidBasis (Fin 2)) = 10 ∧
    Fintype.card (ValidBasis (Fin 3)) = 142 := by
  sorry

/-- Sandwich: the discrete fiber is a lower bound, and for `N ≥ 2` the
    remaining fibers are at most `2^(N * (N - 1) + 3 * 2^(N-2))`. -/
theorem card_valid_bases_bounds (hN : 2 ≤ Fintype.card α) :
    2 ^ (2 ^ Fintype.card α - Fintype.card α) ≤ Fintype.card (ValidBasis α) ∧
    Fintype.card (ValidBasis α) ≤
      2 ^ (2 ^ Fintype.card α - Fintype.card α) +
        2 ^ (Fintype.card α * (Fintype.card α - 1) + 3 * 2 ^ (Fintype.card α - 2)) := by
  sorry

/-- For `N ≥ 10` the total is at most twice the discrete fiber. -/
theorem card_valid_bases_dominated (hN : 10 ≤ Fintype.card α) :
    Fintype.card (ValidBasis α) ≤
      2 * 2 ^ (2 ^ Fintype.card α - Fintype.card α) := by
  sorry

omit [Fintype α] [DecidableEq α] in
/-- `#(N) ∼ 2^(2^N - N)`: the ratio tends to `1`. -/
theorem card_valid_bases_asymptotic :
    Tendsto (fun n : ℕ =>
      (Fintype.card (ValidBasis (Fin n)) : ℝ) / (2 : ℝ) ^ (2 ^ n - n))
      atTop (nhds (1 : ℝ)) := by
  sorry
