/-
Copyright (c) 2026  Lars Warren Ericson.  All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lars Warren Ericson.
-/
import Mathlib.Topology.AlexandrovDiscrete
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Fintype.Powerset
import Mathlib.Data.Set.Card
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Logic.Equiv.Sum

/-!
# The number of topological bases of a finite set

This is the statement of record for a Palomar submission. It states one theorem,
`card_valid_bases`, and the definitions that theorem mentions. It imports only
Mathlib. The proofs are in `CARDB.lean` and are compared against this file by
Comparator.

## Informal claim

Let `α` be a finite type (an `N`-element set). Write `Top(α)` for the set of
topologies on `α`, and write `#(α)` for the number of families
`B ⊆ Set α` that are topological bases on `α` in the usual point-set sense:

1. **Covering.** `⋃₀ B = univ`.
2. **Intersection.** For `U, V ∈ B` and `x ∈ U ∩ V` there is `W ∈ B` with
   `x ∈ W ⊆ U ∩ V`.

These are the two axioms in Mathlib's `IsTopologicalBasis`, without the
`eq_generateFrom` clause that fixes a topology in advance. The topology
generated by `B` is Mathlib's `generateFrom B`.

Every finite topology `τ` is Alexandrov-discrete, so each point `x` has a
minimal open neighbourhood `nhdsKer {x}`. The **canonical minimal basis**
`M_τ` is the set of these neighbourhoods. Bases generating `τ` are exactly
the families `B` with `M_τ ⊆ B ⊆ {U | τ.IsOpen U}`, so the fiber over `τ`
has size `2^(|τ| − |M_τ|)`. Summing over topologies gives

$$
\#(\alpha) = \sum_{\tau \in \operatorname{Top}(\alpha)} 2^{\lvert\tau\rvert - \lvert M_\tau\rvert}.
$$

`card_valid_bases` is that identity: `Fintype.card (ValidBasis α)` equals
that sum. Here `opensOf τ` is the set of `τ`-open sets (so
`ncard (opensOf τ)` is `|τ|`) and `minimalBasis τ` is `M_τ`.

No extra hypothesis is imposed on `α` beyond finiteness and decidable
equality. The empty type is included. The compared theorem depends on
`propext`, `Classical.choice` and `Quot.sound` only.

## How to read this file

The definitions below are the vocabulary of the claim. A reader who wants to
check *what* has been proved should read this file and need not read anything
else. `Solution.lean` imports the sorry-free development in `CARDB.lean`.
-/

open Set TopologicalSpace
open scoped BigOperators

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- A collection of subsets `B` is a topological basis if it covers `α`
    and satisfies the local intersection property. -/
def IsBasis (B : Set (Set α)) : Prop :=
  (⋃₀ B = univ) ∧
  ∀ ⦃U V⦄, U ∈ B → V ∈ B → ∀ x ∈ U ∩ V, ∃ W ∈ B, x ∈ W ∧ W ⊆ U ∩ V

/-- Families of subsets of `α` that are topological bases. `#(α)` is the
    cardinality of this type. -/
def ValidBasis (α : Type*) [Fintype α] := { B : Set (Set α) // IsBasis B }

/-- Open sets of `t`, as a family of subsets. This map is injective, so there
    are only finitely many topologies on a finite type. -/
def opensOf (t : TopologicalSpace α) : Set (Set α) := {U | t.IsOpen U}

omit [Fintype α] [DecidableEq α] in
theorem opensOf_injective :
    Function.Injective (opensOf : TopologicalSpace α → Set (Set α)) :=
  leftInverse_generateFrom.injective

noncomputable instance : DecidableEq (TopologicalSpace α) :=
  opensOf_injective.decidableEq

noncomputable instance : Fintype (TopologicalSpace α) :=
  Fintype.ofInjective opensOf opensOf_injective

noncomputable instance : DecidablePred (IsBasis : Set (Set α) → Prop) :=
  fun _ => Classical.dec _

noncomputable instance : Fintype (ValidBasis α) :=
  Subtype.fintype _

variable (t : TopologicalSpace α)

/-- In a finite topological space, the minimal open neighborhood of `x`
    (Mathlib's `nhdsKer {x}` at topology `t`). -/
abbrev minimalOpen (x : α) : Set α :=
  @nhdsKer α t {x}

/-- The minimal basis `M_T` is the collection of all minimal open neighborhoods. -/
def minimalBasis : Set (Set α) :=
  range (minimalOpen t)

/-- **Main theorem.** The number of topological bases on a finite type `α`
    equals the sum, over all topologies `τ` on `α`, of
    `2^(|τ| − |M_τ|)`, where `M_τ` is the canonical minimal basis of
    minimal open neighbourhoods. -/
theorem card_valid_bases :
    Fintype.card (ValidBasis α) =
      ∑ τ : TopologicalSpace α,
        2 ^ (ncard (opensOf τ) - ncard (minimalBasis τ)) := by
  sorry
